parameters:
#    mongo_lid.example.class: Rplansky\MongoLid\MongoLidBundle\Example

services:
#    mongo_lid.example:
#        class: %mongo_lid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
